Rename folders fro clarity [AEK-269]
arduino-libraries/ArduinoMotorCarrier pull request #36
Opened 2021-07-23 07:17 UTC by aliphys

2021-07-23 13:23 UTC, per1234 requested changes
Please resolve the sketch name mismatch at `examples/Firmware/Flasher.ino`.

2021-07-27 09:19 UTC, per1234 requested changes
The examples paths in the "Compile Examples" CI workflow must be updated at the same time these examples are moved:
- https://github.com/arduino-libraries/ArduinoMotorCarrier/blob/6e8550286713c5a30d053aeca41294644cdea5a7/.github/workflows/compile-examples.yml#L91
- https://github.com/arduino-libraries/ArduinoMotorCarrier/blob/6e8550286713c5a30d053aeca41294644cdea5a7/.github/workflows/compile-examples.yml#L97
- https://github.com/arduino-libraries/ArduinoMotorCarrier/blob/6e8550286713c5a30d053aeca41294644cdea5a7/.github/workflows/compile-examples.yml#L114

2021-07-28 12:47 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/arduino-libraries/ArduinoMotorCarrier?pullRequest=36) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/arduino-libraries/ArduinoMotorCarrier?pullRequest=36) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/arduino-libraries/ArduinoMotorCarrier?pullRequest=36) it.</sub>

2021-07-30 08:03 UTC, per1234 commented on .github/workflows/compile-examples.yml
> +            - examples/MKRMotorCarrier/Test
I'm wondering about this. This causes the sketch to be compiled for all boards, but I would expect that the sketches under `examples/MKRMotorCarrier` would be only for use with MKR boards. I don't know much about these example sketches. Is this sketch intended to be universally applicable to all boards that are compatible with the library?

2021-07-30 09:12 UTC, aliphys commented on .github/workflows/compile-examples.yml
> +            - examples/MKRMotorCarrier/Test
I have removed it from the workflow for now.

2021-07-30 09:25 UTC, per1234 approved these changes

2021-07-30 15:08 UTC, aliphys commented on examples/MKRMotorCarrier/Test/Test.ino
> +  pid1.setGains(25.0f, 0.0f, 3.0f);
pid1.setGains() works with `float `as the input datatype (not `int`). Thanks @Rocketct 😄

2021-07-30 15:12 UTC, aliphys commented on examples/MKRMotorCarrier/Test/Test.ino
> +  pid1.setGains(25.0f, 0.0f, 3.0f);
@per1234 Test.ino should compile correctly now 👍

2021-08-02 07:45 UTC, Rocketct approved these changes

2021-08-02 07:48 UTC, Rocketct reviewed
you added ` examples/NanoMotorCarrier` and `examples/MKRMotorCarrier` but if you don't change the folder name too on the file system, the github action will fail when the will try to find these path

2021-08-02 08:15 UTC, aliphys commented
@Rocketct can you please help me change the required files required for the GitHub Action? I am learning GitHub actions as we go along. 😃

2021-08-02 08:29 UTC, Rocketct commented
https://github.com/arduino-libraries/ArduinoMotorCarrier/tree/master/examples check the names here as you can see here the folder name are MKR and Nano, in your PR you changed the name in the github action as examples/NanoMotorCarrier and examples/MKRMotorCarrier you can do two action:

- modify the folder name and use the new naming
- get back the name to `MKR` and `Nano`

one think @aliphys , did you discused these changes with @ErnestoELC ?
i don't know if this could be a problem with matlab file system management

2021-08-02 08:53 UTC, aliphys commented
@Rocketct I have made the changes in commit https://github.com/arduino-libraries/ArduinoMotorCarrier/pull/36/commits/5dd1e202924dfe93b1aa6537cdcca37609156fec .
Good question about the MATLAB integration, I will ask in our stand-up tomorrow. 👍

2021-08-02 10:30 UTC, Rocketct commented
@aliphys `This commit does not belong to any branch on this repository, and may belong to a fork outside of the repository.`

@aliphys  please double check apparently that commit was not merged, or is not present on master, make that changes and add it to this PR.

but first of all talk with @ErnestoELC this repository cannot be modified so lightly as the other, second and important point because we are using an implicit cast can you and @ErnestoELC check if working or not, because could happened stranger things so we should be sure that is working roperly.

2021-08-03 10:37 UTC, aliphys commented
@Rocketct just spoke with MW, changing the `examples` folder and its content does not influence the Hardware Support Packages.

2021-08-03 12:44 UTC, Rocketct commented
okk perfect so make the changes on the folders name and after the test could be merged

2021-08-03 12:45 UTC, Rocketct commented
ah okk looks like you have made it let me check if the github action pass

2021-08-03 13:15 UTC, Rocketct commented
@per1234 ciao Per can you check the github action? it fails when start to compile the examples

2021-08-03 16:05 UTC, per1234 commented
@Rocketct everything looks as expected to me. There are some compilations that fail, but those are true results.

You will see some of these if you look in the logs:
```
Compiling sketch: examples/MKRMotorCarrier/Motor_test_encoder
Compiling previous version of sketch to determine memory usage change
Compiling sketch: examples/MKRMotorCarrier/Motor_test_encoder
  
  Error during build: opening sketch: no valid sketch found in /home/runner/work/ArduinoMotorCarrier/ArduinoMotorCarrier/examples/MKRMotorCarrier: missing /home/runner/work/ArduinoMotorCarrier/ArduinoMotorCarrier/examples/MKRMotorCarrier/MKRMotorCarrier.ino
  
Error: Compilation failed
Change in flash: N/A
Change in RAM for global variables: N/A
```
The failure of the "Compiling previous version of sketch to determine memory usage change" compilation is normal and expected in this case where the sketch did not exist at that path in the PR's base ref. This second compilation is only done for the sake of the memory usage change report, which is purely informational. The failure of that compilation does not change the CI result. It will start working fine on the next PR after the sketches have been established at their new location.

So focus only on the parts of the logs where the first compilation failed. Those are the ones that cause the ❌ .

---
Note also that there were widespread sporadic GitHub Actions outages all day. My email inbox is full of notifications of spurious workflow failures. These were transient so they were usually passing after I re-ran the jobs. The results you see from this PR are from days ago, before that happened, but if you tried running the CI today then you might have encountered some of these failures. GitHub Actions seems to be increasingly unreliable lately, but at least they get it back up to normal fairly quickly.

2021-08-04 08:03 UTC, Rocketct commented
@per1234 ah ok i though that these ones:
```
Compiling sketch: examples/MKRMotorCarrier/Motor_test_encoder
Compiling previous version of sketch to determine memory usage change
Compiling sketch: examples/MKRMotorCarrier/Motor_test_encoder
  
  Error during build: opening sketch: no valid sketch found in /home/runner/work/ArduinoMotorCarrier/ArduinoMotorCarrier/examples/MKRMotorCarrier: missing /home/runner/work/ArduinoMotorCarrier/ArduinoMotorCarrier/examples/MKRMotorCarrier/MKRMotorCarrier.ino
  
Error: Compilation failed
Change in flash: N/A
Change in RAM for global variables: N/A
```
where fails not that are ok so fine i think that we should focus on portenta's one, but i think that there is a mistake because as far as i remember this library should not be compatible with portenta, can you confirm @aliphys @ErnestoELC ?

2021-08-04 08:24 UTC, aliphys commented
@per1234 I appreciate your explanation of the GH actions. 👍 

@Rocketct Neither boards are compatible with the Portenta, with no plan to provide compatibility in the near future. The Motor Carrier library is designed to work with the Nano 33 IoT (for the [Nano Motor Carrier](https://docs.arduino.cc/hardware/nano-motor-carrier) examples) and all the MKR boards (for the [MKR Motor Carrier](https://docs.arduino.cc/hardware/mkr-motor-carrier)). You can see the list of compatible boards on their relevant docs pages.

**Note:** Nano BLE 33 Sense compatibility is experimental at the moment.

2021-08-04 08:35 UTC, per1234 commented
I'm the one who added the compilation for Portenta H7 to the CI workflow. The reason is because this statement:
https://store.arduino.cc/portenta-h7
>MKR Headers | Use any of the existing industrial MKR shields on it

implied to me that the MKR form factor accessories are intended to be compatible with the Portenta. If the hardware is intended to be compatible then I would expect the software to be compatible as well.

2021-08-04 08:39 UTC, Rocketct commented
@per1234 ah ok mmm for this particular case should not or better was not implemented the software support to this shield and i don't think we want it, but if mandatory we could see how to implement it

2021-08-04 09:03 UTC, per1234 commented
Well, I had to make some educated guesses as to which boards a library was intended to support when it came to setting up the compilation workflows. The point of the workflow is to find example/board combos that don't compile, so I couldn't use a failure to compile as an indication that a board should not be compiled for.

In cases where the CI is configured to compile for a board when there is no intention of  the library supporting that board, I'm always happy to correct the CI configuration. However, in that case I would also suggest the evaluation of whether the supported boards can be more clearly communicated to the user, since if it was unclear to me then it might well be unclear to others.

2021-08-04 10:29 UTC, Rocketct commented
the portenta and the shield are hw incompatible

2021-08-04 10:56 UTC, per1234 commented
PR submitted to remove the Portenta compilations from the CI workflow: https://github.com/arduino-libraries/ArduinoMotorCarrier/pull/39

2021-08-04 13:27 UTC, aliphys commented
> the portenta and the shield are hw incompatible
@Rocketct can you kindly clarify why they are HW incompatible? The Portenta does have all the pins for the MKR boards.

2021-08-04 13:44 UTC, Rocketct commented
A1 and A2 cannot be used as analog out and they are used  to controls motors through the shield, so the shield and the Portenta cannot be used together, so there is no reason to fix the software because at last the hardware will not work than have no sense include it on the .github action because we don't want to check something that is no compatible and will never be fixed

2021-08-04 14:24 UTC, aliphys commented
@Rocketct I have taken a look at the schematic. A1 and A2 pass through the bidirection voltage translator and then connect to IN2 and IN4 respectively. How does the lack of PWM influence the DAC capacilities?

2021-08-04 15:38 UTC, Rocketct commented
are two different things, however in this case the problem is that from A0 to A4 are connected to a switch (analog switch) that allows to choose if use this pin as PXY_C or PXY, really the incompatibility born in the exactly moment when you decide to use the SPI, that i notice is not populated so there could be a chance to make it usable, but in general if you use alone the pins only as a pure analog there shouldn't be any problem, but if you use PXY and meanwhile you want to use PXY_C functionality this is not possible,because from an hw point of view you are allowed to use only one pad at time.

2021-08-05 08:03 UTC, aliphys commented
@Rocketct If we use the labelled pins only for analog input (i.e. use the ADC), then there shouldn't be a HW blocker for using the Portenta with the MKR Motor Carrier, is this correct?
![image](https://user-images.githubusercontent.com/75624145/128314195-387bbfe5-fae8-4533-b07a-641010b7053b.png)

2021-08-05 08:24 UTC, Rocketct commented
no @aliphys  that pin is conneted to sig INX pin, but AFAIK that connector is used to connect motors too rigth? if yes the sig signal shall send some signal to control the motor than analog out.
But looks the SPI have DNP so this means that the SPI is disconnected than this means that this could not affect the compatibility, than the product could works with portenta

2021-08-05 08:38 UTC, aliphys commented
The INX (IN1-IN4) connectors are designated as analog inputs (so the user can attach external sensors) and not used to control the motors.

2021-08-05 08:50 UTC, Rocketct commented
ok so this means that the problem does't exist

2021-08-05 08:54 UTC, aliphys commented
That is great @Rocketct 😃 .
How much work would it take to to make the ArduinoMotorCarrier library compatible with the Portenta H7?

2021-08-05 08:55 UTC, Rocketct commented
wait before this we want that is comaptible? what say the project owner?

2022-12-30 08:12 UTC, merged